if(USE_MULTICORE)
	add_compile_definitions(MULTICORE)
	message(STATUS "")
	message(STATUS "multicore program")
	message(STATUS "")
endif()

if(USE_SANDBOX_ONLY)
	add_compile_definitions(ONLY_SANDBOX)
	message(STATUS "")
	message(STATUS "only sandbox")
	message(STATUS "")
endif()